# Build RCTD
FROM csangara/sp_spatialdwls
##
# RUN export RHOME=/usr/local/lib/R 
# RUN . ~/.bashrc
RUN R -e "if (!require('BiocManager', quietly = TRUE)) install.packages('BiocManager')"

RUN R -e "BiocManager::install('org.Hs.eg.db')"